src/parser.rs

LTS is becoming a real channel, add support fo the new channel identifiers.
BUG=b/284256808
TEST=cargo test

lium: Add support for LTS

---

src/dut.rs

Fix ssh_forwarding error "ssh_stdout was None".
This also fixes a typo in a related error message.

Fix ssh_forwarding error "ssh_stdout was None"

---

src/cmd/build.rs
src/cmd/deploy.rs
src/cmd/lium.bash

This is for the issue #14 . Changing packages list as positional argument for  `lium build` and `lium deploy`, also update lium.bash to complemnt the package name.

14 pass packages list as positional for deploy and build

---

src/cmd/flash.rs
src/cmd/sync.rs
src/main.rs

Use the board name instead of "eve" for looking up version. 'lium sync' will continue use "eve".

flash: Use the board name for looking up version

---

src/cmd/deploy.rs

Add --ab-update option to the lium deploy command. This option is valid only if the host kernel package is deployed.

lium deploy: add ab_update option

---

src/cmd/arc.rs
src/cmd/build.rs
src/cmd/chroot.rs
src/cmd/cl.rs
src/cmd/config.rs
src/cmd/deploy.rs
src/cmd/dut.rs
src/cmd/flash.rs
src/cmd/packages.rs
src/cmd/servo.rs
src/cmd/setup.rs
src/cmd/sync.rs
src/cmd/tast.rs

The help messages are changed to (1) use the imperative form, and (2) provide the intuition of subcommands available. For (2), it does not try to cover all the subcommands. Instead, it aims to provide a hint to the user to figure out which command to further look into.
It now prints:
```
Usage: lium <command> [<args>]
yet another wrapper for CrOS developers. For more information, see: https://chromium.googlesource.com/chromiumos/platform/dev-util/+/refs/heads/main/contrib/lium/ . For Googlers, see go/lium and go/lium-bug
Options:
--help            display usage information
Commands:
arc               control ARC
build             build package(s)
cl                manage CL (Change List)
chroot            run in chroot
config            configure lium
deploy            deploy package(s) …
```

Fix help messages for the top level commands.

---

src/repo.rs

With this, lium will output something like below for my case.
```
Syncing /usr/local/google/home/hidenorik/chromiumos to R117-15572.32.0 ...
Previous CROS version was: R116-15506.0.0
Running repo init with the given version...
repo: reusing existing repo client checkout in /usr/local/google/home/hidenorik/chromiumos
repo has been initialized in /usr/local/google/home/hidenorik/chromiumos
Running repo sync...
repo sync failed.
Updating depot_tools...
depot_tools update failed. Conflict in /usr/local/google/home/hidenorik/local/src/depot_tools
error: Your local changes to the following files would be overwritten by checkout:
repo_launcher
Please commit your changes or stash them before you switch branches.
Aborting
Traceback (most recent call last):
File …
```

repo: don't try to print repo when empty

---

src/chroot.rs
src/util/shell_helpers.rs

With a split in loops, the iterators are always able to continue without
blocking the main thread.

Fix for reading subcommand inputs and processing.

---

src/cmd/deploy.rs

Check whether ~/trunk/ exists or not, if not, use ~/chromiumos/ instead for searching update_kernel.sh script.
The `~/trunk` has been removed by https://chromium-review.googlesource.com/c/chromiumos/chromite/+/4835006

deploy: Switch ~/trunk/ and ~/chromiumos/ in chroot

---

Cargo.lock
Cargo.toml
src/cmd/sync.rs
src/repo.rs

- Draw a simple progress bar by default while running `lium sync`. 
- With the `--verbose` option, `repo sync` output is printed as it is.

Add a progress bar and verbose option

---

.gitattributes

Mark docs/servo_power_monitor/dist/* as generated files to make the review easier. The js files under the dir should be kept checked-in for a while since it is used for github pages (will be replaced by the actions later)

Create .gitattributes to hide generated files from the review by default

---

src/cmd/deploy.rs

Force deploy when running `cros deploy` via `lium deploy`. `cros deploy` started checking if USE flags are matched when deploying and building, and when it is not matched, it asks users to proceed or not (and... the command itself will succeed even if the stdin sends just an EOF, which is not good...), which causes a false success on the lium side. To avoid this, for now, calling `cros deploy` with `--force` flag to continue without that prompt.

Force deploy to avoid failure caused by USE mismatch warnings

---

src/config.rs

- Add the config option indicates that the user is an internal user. 
- Validated when using internal features. 
- Set false by default.

Add `is_internal` config option

---

src/cmd/tast.rs

This cleans up the `lium tast` code and make it update the test list if `--cached` is not specified.

176 update tast test list by default

---

src/cmd/vm.rs

Corrected an error message when the betty script path was incorrectly specified in the vm command.

Fix error message of arc option of vm commad

---

src/cmd/lium.bash

Skip the help message lines which seems not an option.
After applying this fix, lium dut shows only the options or subcommands correctly.
```
$ lium dut 
--help         discover       info           list           pull           setup          vnc
arc_info       do             kernel_config  monitor        push           shell          
```

lium.bash: Fix to ignore the line who has a space in the 3rd char

---

src/cmd/vm.rs
src/config.rs

- Change the `lium vm start` command to launch cloud based VM instances
- Add the config options to get acloudw command parameters
- Separate the process of running betty.sh and the process of running acloudw into functions
Issue: https://github.com/google/lium/issues/87

Support acloud in vm command

---

src/cmd/dut.rs
src/dut.rs

Remove HWID from the list of the default DUT info key to add VM instances (e.g. betty VM) to the DUT list

Remove HWID from default key to add VM instance to DUT list

---

README.md
src/cmd/arc.rs
src/cmd/build.rs
src/cmd/chroot.rs
src/cmd/cl.rs
src/cmd/deploy.rs
src/cmd/dut.rs
src/cmd/flash.rs
src/cmd/lium.bash
src/cmd/packages.rs
src/cmd/servo.rs
src/cmd/sync.rs
src/cmd/tast.rs
src/main.rs
src/repo.rs

- Rename the `--repo` option to specify the directory path
- Use the `--cros` option for ChromeOS paths and the `--arc` option for Android paths

Rename repo option to cros/arc option

---

src/cmd/vm.rs

To keep consistency with the same option of `lium flash`, rename the `--rootfs-verify` option of `lium vm`
https://github.com/google/lium/blob/474ede5379cbcc1279f3fae65f36a682383a1ecd/src/cmd/flash.rs#L110

Rename rootfs_verify option to enable_rootfs_verification

---

src/cmd/arc.rs

adb has to connect to the Android VM before calling logcat to get the result.
TEST=Ran `lium arc logcat --dut $DUT` twice. `adb connect` was called only first time.

Call `adb connect` before calling `adb logcat`

---

src/cmd/config.rs
src/cmd/lium.bash
src/config.rs

- Add the `--branch` subcommand
- Add tab completion of Android branch name
- Use it when the `--branch` option is specified (e.g. `lium vm start` command)

Add tab completion of branch name

---

src/cmd/tast.rs

Check whether the given test pattern matches any test. If not, show the error message.
TEST=lium tast run non-exist.test --dut $DUT

tast: Warn user if given test pattern does not match any test

---

src/cmd/tast.rs

Just warn if user runs a non-cached tast tests. In this case, the test is expected to be in the default bundle (tast-tests).

tast: Just warn if running non-cached tast tests

---

rustfmt.toml

To supress the warning message on cargo fmt
TEST=make check

Replace fn_args_layout to fn_params_layout as the warning says

---

src/cmd/flash.rs

cro3 flash uses signed recovery image and it requires --usb option.

219 cro3 flash recovery should use signed image on usb

---

src/cmd/dut.rs

To make the output stable and easy to lookup

Sort DUT_ID on cro3 dut list --ids

---

src/cmd/build.rs
src/cmd/tast.rs

Remove update_chroot from `tast list` and `build` commands because it is not required anymore.

tast: build: Remove update_chroot

---

src/cmd/arc.rs

Run the python3 script directly instead of using interpreter in `cro3 arc flash`.

arc flash: Run the script file directly

---

scripts/bash_completion_check.sh
src/cmd/cro3.bash

If an option parameter has short and long formats, those are connected with comma and space. e.g. "-v, --verbosity".
This checks the first format ends with ',' (and removes it). In that case, parses the 2nd word as an option.

cro3.bash: Handle if there are short and long options

---

src/cmd/sync.rs
src/cros.rs

The current recommendation is using `stable` branch for development in the ChromiumOS repository. 
https://www.chromium.org/chromium-os/developer-library/guides/development/developer-guide/#sync-to-stable
Therefore, I add `stable` to the supported version formats for `cro3 sync --cros` command.
I initially attempted to make `stable` the default branch for the command, as in #227, but I canceled.
My local testing indicates that the `repo init` command doesn't support using a version manifest with `stable`  specified as a manifest revision.
I was unable to find any document that explains about it.

Support `stable` as a cro3 sync target revision

---

src/cmd/dut.rs
src/dut.rs

Add the options for local port forwarding for each DUT on `cro3 dut monitor`. This allows user to make DUT working as gateway. e.g.
cro3 dut monitor mydut,192.168.111.222:3456
This will map some local port to 192.168.111.222:3456 via mydut.

dut monitor: Support local port forwarding option

---

src/dut.rs

The appropriate timeout depends on the running environment. So it should be configured by `ssh_overrides` configuration key.
If you want to set the timeout as 10 seconds, you can configure it via `cro3 config` as below;
```
cro3 config set ssh_overrides -- "*" "/bin/true" "-o" "ConnectTimeout=10"
```

Remove ConnectTimeout option
