google/cro3

src/dut.rs
BUG=None
TEST=reboot DUT while `lium chroot --dut ${DUT}`
TEST=and the connection was re-established.
=> Fix stall on reconnecting ssh port forwarding

src/cmd.rs, src/cmd/packages.rs, src/repo.rs
Find cros sdk directory from the parents of current directory and add `package list` sub command.
=> Find cros sdk directory smarter from current directory and add package list

LICENSE
This makes the license actually valid.
=> Add missing copyright to LICENSE.

src/cmd/tast.rs
Add --option to `lium tast run` to specify test-specific options. (e.g. --option "-var")
=> tast: Add --option for test-specific options

src/cmd/lium.bash
Complete the (known) DUT name for `lium dut list --remove`
TEST=source lium.bash and `lium dut list --remove` [TAB]
=> lium.bash: Complete DUT name for `lium dut list --remove`

src/dut.rs
Generate a MAC address based serial number and use it if the DUT doesn't have its serial number.
=> lium dut: Add MAC addr based serial number if no serial number

src/cmd/dut.rs, src/dut.rs
This adds a new sub-sub-command to reboot into the other partition.
This shouldn't be terribly slow for local DUTs.
=> dut: add reboot_other

src/cmd/flash.rs, src/cmd/lium.bash
TEST=lium flash --usb --image ${PATH_TO_IMAGE}
=> flash: Support --image arg to specify local chromiumos image file

Cargo.lock, Cargo.toml, src/cache.rs, src/chroot.rs, src/cmd.rs, src/cmd/arc.rs, src/cmd/build.rs, src/cmd/chroot.rs, src/cmd/cl.rs, src/cmd/config.rs, src/cmd/deploy.rs, src/cmd/dut.rs, src/cmd/flash.rs, src/cmd/packages.rs, src/cmd/servo.rs, src/cmd/setup.rs, src/cmd/sync.rs, src/cmd/tast.rs, src/cmd/version.rs, src/config.rs, src/cros.rs, src/dut.rs, src/main.rs, src/servo.rs
=> Migrate from printing error logs to using the tokio tracing crate for logging.

src/servo.rs
Add a link to the official documentation and tips from the real-world
=> servo: Add tips

CHANGELOG.md, Cargo.lock, Cargo.toml
=> add changelog and bump version

src/main.rs
=> Add registry to prepare for multiple layers such as indacitif

Cargo.lock, Cargo.toml, src/cmd/deploy.rs
- small cleanup using scopes in deploy
- extract subfunctions and add cleanup to deploy.rs
=> Small cleanup of deploy.rs

Cargo.lock, Cargo.toml, src/arc.rs, src/chroot.rs, src/cmd/arc.rs, src/cmd/chroot.rs, src/cmd/flash.rs, src/util/shell_helpers.rs
Revert subprogram logging feature because `lium build` doesn't work correctly with it.
=> 110 lium build is stopped

README.md
Commit message body:
```
Add a section that describes about core principles of lium to help contributors understand our goal clearly.
Also, updated the contribution section to include some additional expectations for the pull requests.
```
=> Update README.md to include core principles

CODEOWNERS
Include kalutes@ for docs/ (including power meter thing)
=> Update CODEOWNERS to include kalutes

src/repo.rs
- Get `repo sync` output when running `lium sync`. 
- Print them to stdout.
Issue: #30
=> Show progress while `lium sync` 

docs/servo_power_monitor/package-lock.json, docs/servo_power_monitor/package.json
specify files to run lint & fix to make it work.
TEST=npm install -g typescript webpack webpack-cli TEST=npm install
TEST=webpack
TEST=npm run lint
TEST=npm run fix
=> Fix TypeScript lint

src/repo.rs
Changed from reading output character by character with `Read` to reading all at once with `BufReader` and then creating a byte character iterator.
=> Refactor the process of forwarding output.

CODEOWNERS
Include @brandonpollack23 as a code owner of lium 🙌
=> Update CODEOWNERS to include brandonpollack23

src/cmd/build.rs, src/cmd/tast.rs
=> Do not use local update_chroot.sh

Cargo.lock, Cargo.toml, src/cmd.rs, src/cmd/vm.rs
- Run one-time setup and install necessary dependencies 
- Launch local betty VMs  
Issue: #87
=> Add vm command

src/cmd.rs, src/cmd/board.rs, src/cmd/lium.bash
Add `lium board list` and use it for completion.
=> 92 list known board and complete it

docs/webserial/index.html
Added functionalities which serial console in servo_power_test page to serial_console page.
- close port button
- change the console html from list element to span element
- add ctrl+c command
=> Fix webserial page

src/arc.rs, src/chroot.rs, src/cmd/arc.rs, src/cmd/deploy.rs, src/cmd/flash.rs, src/cmd/vm.rs, src/cros.rs, src/repo.rs
Context: https://github.com/google/lium/pull/147#discussion_r1407064129
=> Migrate from printing log to using tracing crate

docs/servo_power_monitor/index.css, docs/servo_power_monitor/index.html, docs/servo_power_test/index.css, docs/servo_power_test/index.html
Fixed the first tooltip messages in servo_power_monitor and servo_power_test page.
=> Fix tooltip message

src/cmd/dut.rs, src/cmd/vm.rs, src/dut.rs
Add a local betty VM to DUT list when running `lium vm start` command
(I'll create another PR to register cloud based VMs)
=> Add a local betty VM to DUT list when launching it

src/cmd/arc.rs, src/cmd/board.rs, src/cmd/build.rs, src/cmd/chroot.rs, src/cmd/cl.rs, src/cmd/deploy.rs, src/cmd/dut.rs, src/cmd/flash.rs, src/cmd/packages.rs, src/cmd/servo.rs, src/cmd/sync.rs, src/cmd/tast.rs, src/repo.rs
=> Refactor `repo` related functions

src/cmd/flash.rs
Skip fetching the board name from DUT if only `--board` option is specified. This fixes lium not to demand the `--dut` option when both `--usb` and `--board` are specfied correctly.
=> lium flash: Skip getting the board from DUT if only --board is given

src/cmd/cro3.bash
It seems `mapfile` does not work on some environment. So partially revert the changes using `mapfile`.
=> cro3.bash: Fix completion to work

Makefile, scripts/bash_completion_check.sh
Basic bash completion script checker is added.
=> 229 bash completion script is not tested
